name: hokollektor
description: An app for monitoring a solar collector

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: ^2.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  bloc: ^7.1.0
  flutter_bloc: ^7.2.0
  http: ^0.13.3
  connectivity_plus: ^1.1.0
  shared_preferences: ^2.0.7
  crypto: ^3.0.1
  convert: ^3.0.1
  charts_flutter: # ^0.11.0
    git:
      url: git://github.com/google/charts.git
      path: charts_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/login.jpg
    - assets/kollKep.jpg
    - assets/nodemcu.jpg
    - assets/icon.png

  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Black.ttf
          weight: 900
        - asset: fonts/Rubik-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: fonts/Rubik-Bold.ttf
          weight: 700
        - asset: fonts/Rubik-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/Rubik-Italic.ttf
          style: italic
        - asset: fonts/Rubik-Light.ttf
          weight: 300
        - asset: fonts/Rubik-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/Rubik-Medium.ttf
          weight: 500
        - asset: fonts/Rubik-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Rubik-Regular.ttf
          weight: 400