var locale = "en";

void initLocale(String loc) {
  if (localizations.contains(loc))
    locale = loc;
  else {
    locale = "en";
    print("no such localization: $loc");
  }
}

String getText(String textKey) => localizedTexts[locale][textKey];

const localizations = [
  "hu",
//  "sr",
//  "sr_Latn",
  "en",
];

const Map<String, Map<String, String>> localizedTexts = {
  "hu": {
    noInternet: "Nincs Internet Kapcsolat",
    fetchFailed: "Tartalom Letöltése Sikertelen",
    connectionError: "Kapcsolódási Hiba",
    invalidUsername: "Hiba A Felhasználónévben",
    invalidPassword: "Hiba A Jelszóban",
    correctPass: "A jelszónak minimum 8 karakter hosszúnak kell lennie"
        " és tartalmaznia kell betűket és számokat",
    failedToLoadChart: "A Betöltés Sikertelen",
    tempKoll: "Kollektor Hőmérséklete",
    tempOutside: "Kinti Hőmérséklet",
    tempInside: "Benti Hőmérséklet",
    koll: "Kollektor",
    outside: "Kinti",
    inside: "Benti",
    pickInterval: "Válasszon Ki Egy Időtartamot",
    cancel: "Mégse",
    save: "Mentés",
    weeklyChart: "Heti Grafikon",
    dailyChart: "Napi Grafikon",
    hourlyChart: "Egy Órás Grafikon",
    realtimeChart: "Valós Idejű Grafikon",
    customChart: "Egyedi Grafikon",
    home: "Kezdőlap",
    charts: "Grafikonok",
    configureHeader: "Koppintson A Konfigurációhoz",
    chartHeader: "Koppintson A Grafikon Kiválasztásához",
    profiles: "Profilok",
    optimal: "Optimális",
    minimal: "Minimális",
    maximal: "Maximális",
    manual: "Manuális",
    custom: "Egyedi",
    house: "Ház",
    minTemp: "Minimum Hőmérséklet: ",
    maxTemp: "Maximum Hőmérséklet: ",
    tapToReload: "Koppintson Az Újratöltéshez",
    manualConf: "Manuális Konfiguráció",
    vent0: "Ventilátor #0",
    vent1: "Ventilátor #1",
    user: "Felhasználónév",
    pass: "Jelszó",
    stayLoggedIn: "Maradjon Bejelentkezve",
    login: "Bejelentkezés",
    expanded: "Kiterjesztett",
    simplified: "Lecsökkentett",
    noTextAdded: "Nincs Szöveg Megadva",
    invalidUserInfo: "Hibás Jelszó Vagy Felhasználónév",
    onDeg: "on",
  },
  "sr": {},
  "sr_Latn": {},
  "en": {
    noInternet: "No Internet Connection",
    fetchFailed: "Fetch Failed",
    connectionError: "Connection Error",
    invalidUsername: "Invalid Username",
    invalidPassword: "Invalid Password",
    correctPass: "Password minimum length is 8 characters"
        " and must contain numbers and letters",
    failedToLoadChart: "Falied To Load",
    tempKoll: "Collector Temperature",
    tempOutside: "Outside Temperature",
    tempInside: "Inside Temperature",
    koll: "Colector",
    outside: "Outside",
    inside: "Inside",
    pickInterval: "Pick Time Interval",
    cancel: "Cancel",
    save: "Save",
    weeklyChart: "Weekly Chart",
    dailyChart: "Daily Chart",
    hourlyChart: "Hourly Chart",
    realtimeChart: "RealTime Chart",
    customChart: "Custom Chart",
    home: "Home",
    charts: "Charts",
    configureHeader: "Tap To Configure",
    chartHeader: "Tap For More Charts",
    profiles: "Profiles",
    optimal: "Optimal",
    minimal: "Minimal",
    maximal: "Maximal",
    manual: "Manual",
    custom: "Custom",
    house: "House",
    minTemp: "Min Temperature: ",
    maxTemp: "Max Temperature: ",
    tapToReload: "Tap To Reload",
    manualConf: "Manual Configuration",
    vent0: "Fan #0",
    vent1: "Fan #1",
    user: "Username",
    pass: "Password",
    stayLoggedIn: "Stay Logged In",
    login: "Sign In",
    expanded: "Expanded",
    simplified: "Simplified",
    noTextAdded: "No Text Added",
    invalidUserInfo: "Invalid User Information",
    onDeg: "on",
  },
};

const fetchFailed = "fetchFailed",
    invalidUsername = "invalidUsername",
    noInternet = "noInternet",
    connectionError = "connectionError",
    correctPass = "correctPass",
    tempKoll = "tempKoll",
    tempOutside = "tempOutside",
    tempInside = "tempInside",
    koll = "koll",
    outside = "outside",
    inside = "inside",
    cancel = "cancel",
    save = "save",
    home = "home",
    charts = "charts",
    minTemp = "minTemp",
    maxTemp = "maxTemp",
    stayLoggedIn = "stayLoggedIn",
    tapToReload = "tapToReload",
    configureHeader = "configureHeader",
    chartHeader = "chartHeader",
    weeklyChart = "weeklyChart",
    dailyChart = "dailyChart",
    hourlyChart = "hourlyChart",
    realtimeChart = "realtimeChart",
    customChart = "customChart",
    profiles = "profiles",
    optimal = "optimal",
    minimal = "minimal",
    maximal = "maximal",
    manualConf = "manualConf",
    vent0 = "vent0",
    vent1 = "vent1",
    manual = "manual",
    expanded = "expanded",
    simplified = "simplfied",
    onDeg = "onDeg",
    custom = "custom",
    house = "house",
    noTextAdded = "noTextAdded",
    user = "user",
    pass = "pass",
    invalidUserInfo = "invalidUserInfo",
    login = "login",
    pickInterval = "pickInterval",
    failedToLoadChart = "failedToLoadChart",
    invalidPassword = "invalidPassword";
